### PR TITLE
Multiplatform "geok"

### PR DESCRIPTION
**Pull request by terrakok**
Hi! I like you library so I've decided to migrate it to Kotlin Multiplatform:
https://kotlinlang.org/docs/mpp-intro.html

And now it works not only on JVM 🤓 (and unit tests are green for jvm and native targets)
E.g. it can be linked as ios framework or javascript bundle.

Next step is publication as kotlin multiplatform library: https://kotlinlang.org/docs/mpp-publish-lib.html
so kotlin developers could use it in multiplatform projects.

What do you think about the idea?
Is it interesting for you?

### CODE REVIEW

**Comment by piruin** [comment]
@terrakok Thank you for the Interesting Improvement for this library! 

Please fix the issues reported by CI. I waiting to merge this PR

**Comment by terrakok** [comment]
Write me when you publish new multiplatform version I will add it to awesome list: https://github.com/terrakok/kmm-awesome 😉

**Comment by piruin** [comment]
@terrakok this was released on [1.2.0](https://github.com/piruin/geok/releases/tag/1.2.0). Thank you for your contribution. 🥂

**Comment by terrakok** [comment]
Nice!
Another question. What do you think about MavenCentral? It's stable and safe service.
Here is a good article
https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

It's about Android library but there aren't differences for multi platform

**Pull request merged**
